tap "1password/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "ticknical/packages"
brew "automake"
brew "readline"
brew "python@3.9"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "brew-cask-completion"
brew "gawk"
brew "git"
brew "go"
brew "httperf"
brew "libplist"
brew "libtool"
brew "libzip"
brew "mas"
brew "packer"
brew "peco"
brew "zplug"
cask "1password"
cask "1password-cli"
cask "atok"
cask "bartender"
cask "citrix-workspace"
cask "corretto8"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox-developer-edition"
cask "font-fira-code"
cask "font-fontawesome"
cask "font-ricty-diminished"
cask "font-source-code-pro-for-powerline"
cask "gimp"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-japanese-ime"
cask "iina"
cask "jpki-client"
cask "kindle"
cask "myna-portal-ap"
cask "mysqlworkbench"
cask "notion"
cask "nttcom-acr1251cl-driver"
cask "phpstorm"
cask "postman"
cask "sequel-ace"
cask "slack"
cask "sourcetree"
cask "stack-stack"
cask "sublime-text"
cask "the-unarchiver"
cask "townwifi"
cask "visual-studio-code"
cask "xld"
cask "zoom"
mas "Evernote", id: 406056744
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Spark", id: 1176895641
mas "Speedtest", id: 1153157709
mas "stts", id: 1187772509
mas "Tweetbot", id: 1384080005
mas "Twitter", id: 1482454543
mas "ZIPANG", id: 882655968
mas "そら案内", id: 599799247
vscode "amazonwebservices.aws-toolkit-vscode"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-docker"
vscode "MS-CEINTL.vscode-language-pack-ja"
vscode "ms-vscode-remote.remote-containers"
vscode "shardulm94.trailing-spaces"
