name: Check Brewfile

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,15 * *'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0

    - name: brew bundle install test
      run: |
        MAS_APPS="$(cat ./.Brewfile | grep -v brew | grep mas | sed 's/^.*"\(.*\)".*$/\1/' | tr '\n' ',')"
        export HOMEBREW_BUNDLE_MAS_SKIP="$MAS_APPS"
        export HOMEBREW_BUNDLE_BREW_SKIP="awscli go"
        brew bundle install --file ./.Brewfile
