name: Check Brewfile

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,15 * *'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0

    - name: brew bundle install test
      run: |
        export HOMEBREW_BUNDLE_BREW_SKIP="awscli go"
        sed -i.bak -e '/^mas/d' -e '/^vscode/d' .Brewfile 
        brew bundle install --file ./.Brewfile
